#!/bin/sh
# This file is part of the Drups.io Docker.
#
# (c) 2021 Drups.io <dev@drups.io>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# Written by Temuri Takalandze <temo@drups.io>, April 2021

docker exec -i "$(docker ps --filter name="_application_back" --format "{{ .ID }}")" \
  sh -c 'cd  /var/www/html && .husky/commit-msg'
